# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "attachments", :force => true do |t|
    t.column "memo_id",      :integer
    t.column "name",         :string,  :limit => 64
    t.column "size",         :integer
    t.column "content_type", :string,  :limit => 64
    t.column "content",      :binary
  end

  create_table "memos", :force => true do |t|
    t.column "created_at", :datetime
    t.column "text",       :string,   :limit => 256
    t.column "location",   :string,   :limit => 256
  end

end
